name: Continuous Integration

on:
  # PR到main分支时触发
  pull_request:
    branches: [ main ]
  # 推送到任何分支时触发（除了main，main由deploy.yml处理）
  push:
    branches-ignore: [ main ]

jobs:
  # 代码检查和构建测试
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: BUILD
        run: |
          MODID=${{ github.event.repository.name }}
          echo "MODID: $MODID"
          . ./build.sh
          
      - name: Check build size
        run: |
          echo "Build completed successfully"
          ls -la dist/
          du -sh dist/
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/

  # 代码质量检查
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check file structure
        run: |
          echo "Checking project structure..."
          find src -name "*.js" | head -10
          find src -name "*.css" | head -10

      - name: Validate Vite config
        run: |
          echo "Validating Vite configuration..."
          npx vite --version
          node -e "console.log('Vite config validation passed')"
          
